#Application properties
spring:
  application:
    name: MicroFreelance-Backend
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

security:
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 86400000 # 24h
    refreshTokenExpiration: 2592000000 #30days


stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}

aws:
  s3:
    bucket: ${AWS_S3_BUCKET:}
    region: ${AWS_S3_REGION:us-east-1}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
